version: '3.4'

services:
    
  blog.db:
      container_name: blog.db
      image:  mcr.microsoft.com/azure-sql-edge
      environment:
        MSSQL_USER: SA
        SA_PASSWORD: "MyPass@word"
        ACCEPT_EULA: "1"
        MSSQL_PID: "Developer"
      ports:
        - "1433:1433"

  mssqltools:
      container_name: blog.mssqlTools
      image: mcr.microsoft.com/mssql-tools
      depends_on:
        - blog.db
      volumes:
        - ./mssql/1-SetupStructure.sql:/tmp/1-SetupStructure.sql
        - ./mssql/init-db.sh:/tmp/init-db.sh
      command: /bin/bash ./tmp/init-db.sh
